### ISSUE TITLE
Man pages are not installed by default

### ISSUE THREAD

**Issue by jcayouette** [moio/sumaform#108]
SUMA servers created with sumaform do not have man packages installed by default. This could be useful for both documentation and developers.

**Comment by MalloZup** [comment]
for me this is a custom request. The design of sumaform is to be minimal as possible. i didn't need man pages so often

**Comment by moio** [comment]
I guess it's OK to add them to servers only, with developer settings only.

The strive to minimalism is more on minions, which add up gigabytes quickly in big cloud setups.

**Comment by MalloZup** [comment]
@jcayouette please provide the man pkg you want to be installed, so we can tsckle the issue more concretely

**Comment by jcayouette** [comment]
Just the normal man package is missing. so 
```zypper in man```

**Comment by jcayouette** [comment]
Lets just close it, I can install them myself and I agree with simplicity.

**Comment by MalloZup** [comment]
thx
