### ISSUE TITLE
sumaform breaks docker networking

### ISSUE THREAD

**Issue by kkaempf** [moio/sumaform#145]
Running `terraform apply` breaks Docker networking. Packets from a container do not get routed any more.

**Comment by MalloZup** [comment]
@kkaempf  are you running that on prod or on localhost with docker and some containers? Can you post your .tf file, without pwd

**Comment by MalloZup** [comment]
@kkaempf  is this still actual? or we can close it? thank you

**Comment by moio** [comment]
I have done this recently and it did not create problems. We need more detailed information so I am closing this now, @kkaempf feel free to reopen or contact me directly if it happens again.
