### ISSUE TITLE
Replace phantomjs with chromium headless

### ISSUE THREAD

**Issue by kkaempf** [moio/sumaform#146]
https://drivy.engineering/running-capybara-headless-chrome/

**Comment by moio** [comment]
To me this is not really a sumaform issue, it is essentially a spacewalk-testsuite-base issue. The dependency is defined here:

https://github.com/SUSE/spacewalk-testsuite-base/blob/master/Gemfile#L8

Closing, and re-opening in spacewalk-testsuite-base.

**Comment by moio** [comment]
https://github.com/SUSE/spacewalk-testsuite-base/issues/314
