### ISSUE TITLE
Start/ensure that qemu-agent is up and running in image/host

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#148]
recently  in slow host (like for the 3.1 testsuite) i discovered that the machines 
were not deployed.

see (https://ci.suse.de/user/manager/my-views/view/cucumber-manager/job/manager-3.1-reference-host/68/console)

After some investigation, found that we need to have "qemu-agent" service running.
https://build.suse.de/package/view_file/Devel:Galaxy:Terraform:Images/sles12sp2/sles12sp2.kiwi?expand=1
In kiwi  and salt, i don't see this

**Comment by moio** [comment]
It is there, see line 32:

https://build.suse.de/package/view_file/Devel:Galaxy:Terraform:Images/sles12sp2/config.sh?expand=1

Can you inspect the VM and verify the package is not there or the service is not started? Does starting it solve the issue?

**Comment by MalloZup** [comment]
```suma-refhead-srv:~ # systemctl status qemu-ga
● qemu-ga.service - QEMU Guest Agent
   Loaded: loaded (/usr/lib/systemd/system/qemu-ga.service; static; vendor preset: disabled)
   Active: active (running) since Mi 2017-07-12 12:08:16 CEST; 1h 54min ago
     Docs: http://wiki.qemu.org/Features/QAPI/GuestAgent
 Main PID: 1001 (qemu-ga)
    Tasks: 1 (limit: 512)
   CGroup: /system.slice/qemu-ga.service
           └─1001 /usr/bin/qemu-ga

Jul 12 12:08:16 linux systemd[1]: Started QEMU Guest Agent.
suma-refhead-srv:~ # uptime
 14:02  up   1:54,  2 users,  load average: 0,06, 0,27, 0,73
```

**Comment by MalloZup** [comment]
closing
