### ISSUE TITLE
DOC: explain briefly how to test a salt.state for dev. sumaform

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#150]
scp/rsync them to your deployed machine in /root/salt and then `salt-call --local --file-root=/root/salt state.highstate`

**Comment by moio** [comment]
I guess this is: https://github.com/moio/sumaform/blob/master/TROUBLESHOOTING.md#q-how-do-i-re-apply-the-salt-state-that-was-used-to-provision-the-machine

Am I missing anything?

**Comment by MalloZup** [comment]
No thx, maybe is not visible but is there
