### ISSUE TITLE
Cannot access to spice display of VMs running on a remote host

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#172]
When accessing from virt-manager to VMs spawn by sumaform running on a remote KVM host, I can see the list of VMs, but not their display. Following message appears:
``````
Error connecting to the graphical console: the guest is on a distant host, but is
configured only for connexions to local file descriptors
``````

A workaround is to go to the settings tab of the VM, choose "Spice display" in the left side menu, and in front of "Listen to:", change "None" into "Address". Then, after a reboot of the VM (needed to take into account the new setting), it works, I can see the display.

Translated into XML settings, it means that:
``````
<graphics type='spice'>
    <listen type='none'/>
</graphics>
``````
should be changed into:
``````
<graphics type='spice' autoport='yes' listen='0.0.0.0'>
    <listen type='address' address='0.0.0.0'/>
</graphics>
``````

The error is most probably in the libvirt plugin for terraform, but it seems it is already fixed there, but the new version is not used in sumaform yet.

**Comment by moio** [comment]
New terraform and terraform-provider-libvirt merged in `master`, I tested this and it works now. Closing, thanks for the investigation and reporting!
