### ISSUE TITLE
tmux not found on sles12sp1

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#192]
tl.controller.libvirt_domain.domain (remote-exec): ----------
module.ctl.controller.libvirt_domain.domain (remote-exec):           ID: extra_pkgs
module.ctl.controller.libvirt_domain.domain (remote-exec):     Function: pkg.installed
module.ctl.controller.libvirt_domain.domain (remote-exec):       Result: False
module.ctl.controller.libvirt_domain.domain (remote-exec):      Comment: An error was encountered while installing package(s): Zypper command failure: Running as unit run-2747.scope.
module.ctl.controller.libvirt_domain.domain (remote-exec):               Package 'tmux' not found.
module.ctl.controller.libvirt_domain.domain (remote-exec):      Started: 18:17:03.538315
module.ctl.controller.libvirt_domain.domain (remote-exec):     Duration: 708.66 ms
module.ctl.controller.libvirt_domain.domain (remote-exec):      Changes:   
module.ctl.controller.libvirt_domain.domain (remote-exec): 
module.ctl.controller.libvirt_domain.domain (remote-exec): Summary for local

**Comment by MalloZup** [comment]
@cbbayburt

**Comment by mbologna** [comment]
I think we should resort to screen due to tmux not available on SLES (without adding extra repos).

**Comment by MalloZup** [comment]
Ok for me

**Comment by moio** [comment]
Patch reverted
