### ISSUE TITLE
Put a FQDN in /etc/hostname on clients 

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#195]
Hi,

The clients get created with this in ```/etc/hostname``` :
```
  ebi3-clisles12sp2
```
it should read instead:
```
   ebi3-clisles12sp2.tf.local
```
otherwise ```hostname -f``` does not work after a reboot:
```
  $ hostname -f
  ebi3-clisles12sp2.tf.local
```
before reboot, but:
```
  $ hostname -f
  hostname: Nom ou service inconnu
```
after a reboot.

This makes cucumber refuse to work after a reboot with message:
```
‎ no full qualified hostname for node (RuntimeError)
```
which is pretty annoying :smile: .

**Comment by moio** [comment]
AFAICS both short names and long names are correct in `/etc/hostname`, and people tend to like the shortname in `/etc/hostname` better. In order for this to work correctly DNS resolution must work properly, or proper `/etc/hosts` lines must be in place as a "workaround".

I did notice we did not have adequate lines in `/etc/hosts` for ipv6, and that some of the configuration was wrong in this respect. I fixed all of this in current master, and tested various OSs with minions, clients and proxies across reboots - all seems to work.

I am closing this now, please reopen if you can reproduce this on current master.

Thanks for reporting

**Comment by Bischoff** [comment]
Thanks for the changes Silvio.

I'm not sure it will work this way (with extra IPv6 entry in /etc/hosts). But we'll know pretty soon if it is not fixed, because I hit this problem quite often.

In case it is not fixed, what needs to be done is to change
```
permanent_hostname:
  file.managed:
    - name: /etc/hostname
    - contents: {{ grains['hostname'] }}
```
to include ```.{{ grains['domain'] }}``` in ```salt/default/hostname.sls```.
