### ISSUE TITLE
find "safe" solution for git passwords

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#224]
Currently,when someone uses the controller node, he needs to put git credentials and SCC credentials in ```main.tf```

Consequences:
1) the password is in a file which could be read by unauthorized person;
2) it appears on the screen when doing "terraform apply";
3) it might appear in the process list (?);
4) it is transmitted unencrypted.

The 2) might be mitigated by using environment variables, 4) by using pillars, etc.

**Comment by cbbayburt** [comment]
A relatively safer workaround would be to create access tokens for yourself with limited access:
https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line

It is also a must if you're using 2FA with GitHub.

**Comment by moio** [comment]
We are already using tokens in place of passwords, and the need for a password will be removed as soon as the SUSE Manager git repo is made publicly available.

**Comment by MalloZup** [comment]
i'm closing this issue because we will fix this once we go opensourced  there will be no need for adding a pwd

**Comment by juliogonzalez** [comment]
Even after making the repository public, most probably we'll still have a private one to develop bugfixes for security embargoes

**Comment by moio** [comment]
I am closing this as I do not see it as a sumaform issue. One can use Terraform's support for environment variables to leave credentials out of `main.tf`, eg:

```bash
export TF_VAR_mysecret='123password'
```

Then in `main.tf`:
```hcl
module "base" {
  source = "./modules/libvirt/base"

  cc_username = "username"
  cc_password = "${mysecret}"
```

About other aspects, they are out of scope for sumaform, see the [DESIGN](https://github.com/moio/sumaform/blob/master/DESIGN.md#goal) goals.

I am not against changing the goals, but this needs structured discussion and efforts as I cannot drive such an effort myself.

**Comment by juliogonzalez** [comment]
@moio great! This is enough to get this unlocked to make the runner public.

**Comment by juliogonzalez** [comment]
For reference, at this with terraform 0.11 this doesn't seem to work:

```
Error: module.base.var.cc_password: invalid variable syntax: "SCC_PASSWORD". Did you mean 'var.SCC_PASSWORD'? If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.

Error: module.base.var.cc_username: invalid variable syntax: "SCC_USER". Did you mean 'var.SCC_USER'? If this is part of inline `template` parameter
then you must escape the interpolation with two dollar signs. For
example: ${a} becomes $${a}.
```

If I use `var.SCC_USER` and `var.SCC_PASSWORD`:
```
Error: module 'base': unknown variable referenced: 'SCC_USER'; define it with a 'variable' block

Error: module 'base': unknown variable referenced: 'SCC_PASSWORD'; define it with a 'variable' block
```
To use the variables, defining them at the main.tf is required:
```
variable "SCC_USER" {
  type = "string"
}

variable "SCC_PASSWORD" {
  type = "string"
}
```
And then they can be used as `${var.myvar}`:
```
module "base" {
  source = "./modules/libvirt/base"

  cc_username = "${var.SCC_USER}"
  cc_password = "${var.SCC_PASSWORD}"
```

**Comment by Bischoff** [comment]
`TF_VAR_xxx` environment variables are nice, and i will move to them on my test machines.

However, we need to use them on sumaform test runner as well, and declare them in environment of m226, don't we?

@juliogonzalez am I saying crap? If what I say makes sense, then we need a new task, against the runner this time, don't we?
