### ISSUE TITLE
No "image" parameter for proxy module

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#227]
When you use the proxy module, you get a SLE12 SP2 system. If you want to select a different value, you get the following error message:
```
module root: module proxy: image is not a valid parameter
```

For the other modules, ```image = ``` parameter is the way to select an image. It shoud work for the proxy too.

Note: SLES 12 SP3 is a requirement for suse manager 3.2 proxy:
```
Problem: nothing provides product(SLES) >= 12.3 needed by product:SUSE-Manager-Proxy-3.2-0.x86_64
```

**Comment by Bischoff** [comment]
In ```sumaform/modules/libvirt/suse_manager*/main.tf``` the default image for ```head``` and ```test`` is SP2 and not SP3. I can fix fix in a quick PR.

I don't know if that's enough as a fix, or if we should still offer a choice.

**Comment by moio** [comment]
Same rule should apply for proxies and servers alike: default image should be automatically chosen depending on product version, overridable for those products that support more than one (this happens for example in 3.1 but currently not in 3.2).

If the user overrides the default image selection with an invalid one, an error like the one you pasted should be produced.

**Comment by Bischoff** [comment]
The default was wrong and will get fixed in the PR.

The problem for the proxy is that the image is apparently not overridable (unlike the server): ```image is not a valid parameter```.

Maybe it's a correct strategy, as I can't figure out a case where we can have more than one allowed version for the proxy.

**Comment by MalloZup** [comment]
@Bischoff  can we close this? feel free to close it. TIA

**Comment by Bischoff** [comment]
I think so. Closing.
