### ISSUE TITLE
Tools repository should not be in the server

### ISSUE THREAD

**Issue by ktsamis** [moio/sumaform#247]
After creating some VM's with sumaform, with no additional repos or packages.
To be clear I used 3.0-released for the server.
I do ```zypper patch``` and I have conflicts as if it is a proxy. I checked the repos and these are enabled:

```
qam-srv:~ # zypper lr
Repository priorities in effect:                                                                                                                                                   (See 'zypper lr -P' for details)
      97 (raised priority)  :  2 repositories
      99 (default priority) :  5 repositories

# | Alias                                  | Name                                   | Enabled | GPG Check | Refresh
--+----------------------------------------+----------------------------------------+---------+-----------+--------
1 | SLE-12-SP2-x86_64-Pool                 | SLE-12-SP2-x86_64-Pool                 | Yes     | (r ) Yes  | No     
2 | SLE-12-SP2-x86_64-Update               | SLE-12-SP2-x86_64-Update               | Yes     | (r ) Yes  | No     
3 | SLE-Manager-Tools-SLE-12-x86_64-Pool   | SLE-Manager-Tools-SLE-12-x86_64-Pool   | Yes     | (r ) Yes  | No     
4 | SLE-Manager-Tools-SLE-12-x86_64-Update | SLE-Manager-Tools-SLE-12-x86_64-Update | Yes     | (r ) Yes  | No     
5 | SUSE-Manager-3.0-x86_64-Pool           | SUSE-Manager-3.0-x86_64-Pool           | Yes     | (r ) Yes  | No     
6 | SUSE-Manager-3.0-x86_64-Update         | SUSE-Manager-3.0-x86_64-Update         | Yes     | (r ) Yes  | No     
7 | home_SilvioMoioli_tools                | home_SilvioMoioli_tools                | Yes     | (r ) Yes  | No     

```
The tools repository should not be in the server. It comes from line 228 in sumaform/salt/default/repos.sls that adds the tools repository and is not in an if jinja statement.

By removing the repos immediately on creation there is no conflict.

So the solution would be either to move the lines for tools in all the other modules that need them, or put an if statement that excludes them for server. I think the second is easier.
Thanks to @Bischoff for helping narrow this down.

**Comment by ktsamis** [comment]
Preparing a pull request that adds a conditional for ```role=!suse_manager_server``` to only then add the repos .

**Comment by Bischoff** [comment]
To reproduce the problem, just deploy with `3.0-released` in testsuite mode, and type `zypper patch` twice. There will be a missing dependencies on spacewalk libraries.

**Comment by moio** [comment]
> It comes from line 228 in sumaform/salt/default/repos.sls that adds the tools repository and is not in an if jinja statement.

I am missing something here, as I do not find anything related in that location:

https://github.com/moio/sumaform/blob/master/salt/default/repos.sls#L228

> Preparing a pull request that adds a conditional for role=!suse_manager_server to only then add the repos .

The actual lines adding the repo are:

https://github.com/moio/sumaform/blob/master/salt/suse_manager_server/repos.sls#L160-L168

```jinja
{% if grains['for_testsuite_only'] or grains.get('monitored') | default(false, true) %}
tools_repo:
  file.managed:
    - name: /etc/zypp/repos.d/home_SilvioMoioli_tools.repo
    - source: salt://suse_manager_server/repos.d/home_SilvioMoioli_tools.repo
    - template: jinja
    - require:
      - sls: default
{% endif %}
```

The tools repo is definitely needed at least for the Prometheus probes, so the `monitored` part of the guarding conditional is correct. At the moment I can't recall and I can't see why it should be needed for the testsuite, so in case you are sure it is not needed there feel free to open a PR to remove that part.

Hope this helps

**Comment by ktsamis** [comment]
Ok sorry for the misunderstanding, when I said tools repo, I mean the SUSE Manager client tools repo. Your home tools are not what I am talking about. The lines that add the repo are:
from:
https://github.com/moio/sumaform/blob/master/salt/default/repos.sls#L226
until: 
https://github.com/moio/sumaform/blob/master/salt/default/repos.sls#L236
```
tools_pool_repo:
  file.managed:
    - name: /etc/zypp/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Pool.repo
    - source: salt://default/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Pool.repo
    - template: jinja

tools_update_repo:
  file.managed:
    - name: /etc/zypp/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Update.repo
    - source: salt://default/repos.d/SLE-Manager-Tools-SLE-12-x86_64-Update.repo
    - template: jinja

```
Also any idea on how to make it conditional? I have been trying since yesterday and either it doesn't render my jinja (my bad) or it caused tracebacks on the other hosts that should have the repo. If you have any recommendation on the conditional line please let me know. Also the same "uncoditional repos" are there for SLE11 but since no server is based on SLE11 I think we can safely ignore them.

**Comment by moio** [comment]
Those are needed to provide Salt at terraform deployment time (in the right Salt version), so they cannot be removed before deployment is done.

The only thing we can do is to disable them or remove them after SUSE Manager is fully installed. That's not the best thing when it comes to Salt, but at least it can be done and will address your problem.

**Comment by ktsamis** [comment]
That should be easy for me to do then, I thought about doing that before but didn't want to have such a "hacky" way of doing things. Now that I have a reason to do it this way, I'm happy :)

But doesn't salt get provided in the SUSE Manager server repos as well? Not that I'm arguing your point since I'm obviously not as familiar with sumaform as you, who created it, just trying to understand.

**Comment by moio** [comment]
Nope, SUSE Manager Server repos contain `salt-master`, not `salt-minion`! :smile:

**Comment by ktsamis** [comment]
Ah so the minion is needed for the provisioning, now I get it, thanks. I am writing the state now, as soon as I know it's fine I will open a PR for your reviewing pleasure :smile:

**Comment by MalloZup** [comment]
@ktsamis is this issue fixed ?

**Comment by ktsamis** [comment]
Yes, it is, closing now.
