### ISSUE TITLE
Create disks/images on demand

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#26]
At moment we create all the images/disk, like sle12sp1, opensuse42.1, centos,

we should be able to specifiy that we want only to create a leap42.1 for example.

**Comment by cbbayburt** [comment]
+1 for that. I had to comment out unneeded images in `modules/libvirt/base/main.tf` manually.

**Comment by jcayouette** [comment]
+1

**Comment by moio** [comment]
Fixed in #98
