### ISSUE TITLE
Get rid of var server.configuration for client and minion

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#27]
At moment, we have this variable that expect :  

https://github.com/moio/sumaform/blob/master/main.tf.libvirt-testsuite.example#L34

the serverhostname.

With this variable, we loose like 20 Min in automation, because the server, client, minion are not created in parallel, because of this dependency, that in the testsuite mode isn't used.

We should get rid of this variable, in order to spawn the server,client, minion in parallel. (and other new-coming machines) control-node need the other machines, this is ok

**Comment by MalloZup** [comment]
https://github.com/moio/sumaform/pull/28
fix this issue

**Comment by moio** [comment]
I agree we have a problem here but do not agree with the solution.

See discussion on the PR :smile:

**Comment by MalloZup** [comment]
OK, FIXED now, as you saw in the PR 💃

**Comment by MalloZup** [comment]
merged closing
