### ISSUE TITLE
Support terraform v0.11

### ISSUE THREAD

**Issue by aaannz** [moio/sumaform#285]
The [repository](https://download.opensuse.org/repositories/systemsmanagement:/sumaform/SLE_12_SP3/) mentioned in [readme](https://github.com/moio/sumaform/blob/master/README.md) to download terraform from does not have terraform rpm anymore and building is disabled. I went to use [Virtualization:containers](http://download.opensuse.org/repositories/Virtualization:/containers/SLE_12_SP3/) instead, but there is terraform v0.11 already.

Terraform v0.11 does not work with current configuration examples, primarily because of `version` being reserved word now. ( See https://github.com/hashicorp/terraform/issues/16859 ).
Are there any plans to support new version?

**Comment by moio** [comment]
I am sorry about the incorrect state of the repository, packages are now ready.

There is a general plan to routinely update the Terraform version we support. It is not really practical to keep working on the very latest, as the Terraform team releases every two weeks and often the changes are breaking our testsuites, so we only do that from time to time.

So this will surely come at some point.

**Comment by aaannz** [comment]
Thanks, that's understandable.
Anyway, I managed to make it work with v0.11.3 so just as a heads up what I had to do:
* rename 'version' (I choose to rename it to 'release') 
* remove `running = "${var.running}"` line from modules/libvirt/host/main.tf. libvirt provider was complaining about not existing 'running' variable.

Complete diff:

```diff
diff --git a/modules/libvirt/host/main.tf b/modules/libvirt/host/main.tf
index 6464e2d..40f063f 100644
--- a/modules/libvirt/host/main.tf
+++ b/modules/libvirt/host/main.tf
@@ -19,7 +19,7 @@ resource "libvirt_domain" "domain" {
   name = "${var.base_configuration["name_prefix"]}${var.name}${var.count > 1 ? "-${count.index  + 1}" : ""}"
   memory = "${var.memory}"
   vcpu = "${var.vcpu}"
-  running = "${var.running}"
+//  running = "${var.running}"
   count = "${var.count}"

   // base disk + additional disks if any
diff --git a/modules/libvirt/suse_manager/main.tf b/modules/libvirt/suse_manager/main.tf
index 429e9db..4352da9 100644
--- a/modules/libvirt/suse_manager/main.tf
+++ b/modules/libvirt/suse_manager/main.tf
@@ -23,7 +23,7 @@ module "suse_manager" {
   gpg_keys = "${var.gpg_keys}"
   grains = <<EOF

-version: ${var.version}
+version: ${var.release}
 cc_username: ${var.base_configuration["cc_username"]}
 cc_password: ${var.base_configuration["cc_password"]}
 database: ${var.database}
@@ -46,7 +46,7 @@ traceback_email: ${var.traceback_email}
 EOF

   // Provider-specific variables
-  image = "${var.image == "default" ? lookup(var.images, var.version) : var.image}"
+  image = "${var.image == "default" ? lookup(var.images, var.release) : var.image}"
   memory = "${var.memory}"
   vcpu = "${var.vcpu}"
   running = "${var.running}"
@@ -57,6 +57,6 @@ output "configuration" {
   value {
     id = "${module.suse_manager.configuration["id"]}"
     hostname = "${module.suse_manager.configuration["hostname"]}"
-    version = "${var.version}"
+    release = "${var.release}"
   }
 }
diff --git a/modules/libvirt/suse_manager/variables.tf b/modules/libvirt/suse_manager/variables.tf
index df36b4d..e70d670 100644
--- a/modules/libvirt/suse_manager/variables.tf
+++ b/modules/libvirt/suse_manager/variables.tf
@@ -8,7 +8,7 @@ variable "name" {
   type = "string"
 }

-variable "version" {
+variable "release" {
   description = "One of: 2.1-released,  2.1-nightly, 3.0-nightly, 3.0-released, 3.1-released, 3.1-nightly, head, test"
   type = "string"
 }
```

**Comment by MalloZup** [comment]
thx @aaannz  i split this in 2 tasks,

- [ ] https://github.com/moio/sumaform/issues/353
- [ ] and the version rename later

**Comment by MalloZup** [comment]
@moio  `release_version` would fit for you a new var?

If we go in this direction, we need to:
- [ ] update sumaform to latest terraform-libvirt-plugin (for $running fix )
- [ ]  update prod file
- [ ]  send email to galaxy and user to update the main.tf  files for chaining var
