### ISSUE TITLE
Race condition by creating disk images. 

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#29]
## How to reproduce.

take for example the main.tf.testing from sumaform

The machines aren't successful created, usually we have a problem with the control-node, but can happens also with other disks

* libvirt_volume.main_disk: Can't retrieve volume dma-sles12sp1.

@moio 
I don't know if this issue is due to sumaform, i'm thinking that is due to the libvirt plugin, even, this issue is a part of sumaform, because it affects it's basic usage. As a user, we have now a 50% race condition in a Server or Locally. 

```Terraform taint``` can be a workaround, but is not a valid one for daily usage

**Comment by MalloZup** [comment]
This issue, i had this when creating the control-node machine. on 1/10 cases

**Comment by MalloZup** [comment]
we have the errorr ```* libvirt_volume.main_disk: Can't retrieve volume tssles12sp1``
but the the image is there, i checked it now, 
-rw-r--r-- 1 qemu qemu  296878080 24. Nov 18:52 tssles12sp1

**Comment by MalloZup** [comment]
/sumaform30> terraform get
Get: file:///home/jenkins/sumaform30/modules/libvirt/base
Get: file:///home/jenkins/sumaform30/modules/libvirt/suse_manager
Get: file:///home/jenkins/sumaform30/modules/libvirt/client
Get: file:///home/jenkins/sumaform30/modules/libvirt/minion
Get: file:///home/jenkins/sumaform30/modules/libvirt/control_node
Get: file:///home/jenkins/sumaform30-refhost/modules/libvirt/host
Get: file:///home/jenkins/sumaform30-refhost/modules/libvirt/host
Get: file:///home/jenkins/sumaform30-refhost/modules/libvirt/host
Get: file:///home/jenkins/sumaform30-refhost/modules/libvirt/host

**Comment by MalloZup** [comment]
https://github.com/moio/sumaform/pull/35

**Comment by moio** [comment]
Closing as this is definitely not a sumaform issue. We have to investigate this at the plugin or Terraform level.
