### ISSUE TITLE
Adding image at the beginning of the list causes recreation of all images

### ISSUE THREAD

**Issue by cbbayburt** [moio/sumaform#292]
Imagine we have applied a configuration with the following line in `main.tf`
```
  ...
  images = ["sles12sp2", "sles12sp3"]
```
After the creation, I modify the list like below and try to run the new config:
```
  ...
  images = ["sles12sp1", "sles12sp2", "sles12sp3"]
```

When I run `terraform plan` now, I see the following change for all the existing images:
```
-/+ module.base.libvirt_volume.volumes[0] (new resource required)
      id:     "/var/lib/libvirt/images/cb-sles12sp2" => <computed> (forces new resource)
      name:   "cb-sles12sp2" => "cb-sles12sp1" (forces new resource)
      ...

-/+ module.base.libvirt_volume.volumes[1] (new resource required)
      id:     "/var/lib/libvirt/images/cb-sles12sp3" => <computed> (forces new resource)
      name:   "cb-sles12sp3" => "cb-sles12sp2" (forces new resource)
      ...

  + module.base.libvirt_volume.volumes[2]
      id:     <computed>
      name:   "cb-sles12sp3"
      ...
```
Basically, the problem is that terraform tries to shift all images in the list by recreating them under the new index. This is only some inconvenience because if I add a new image in the end of the list, there is no problem.

I'm not sure if this is easily fixable or it's restricted by terraform's capabilities tough.

**Comment by moio** [comment]
The only solution I can think of is to avoid defining images as counted resources:

https://github.com/moio/sumaform/blob/master/modules/libvirt/base/main.tf#L5

but to declare them all separately. Then you could use the `contains` function to decide whether they should be deployed or not (setting `count` to `0` or `1` depending on the `image` array in `base`).

Thanks for pushing me into thinking about a good solution to this problem.

Now we need a PR :smile:

**Comment by moio** [comment]
I plan to implement this next time a change in the image set are necessary.
