### ISSUE TITLE
Ability to create a sumaform machine with multiple network interfaces

### ISSUE THREAD

**Issue by aaannz** [moio/sumaform#295]
For SMR our branch minion usually needs two interfaces, one connected to suma master, one to isolated network (we provide our own DHCPd service).

I know, that this is doable in terraform resource, but is it doable in sumaform module? Can it be added if not?

What I imagine is to be able to set e.g. interface.1 to use default libvirt net and interface.2 to use bridge (and not wait for dhcpd leases, since it will be statically configured by our salt states).

**Comment by MalloZup** [comment]
@aaannz  i think this got fixed feel free to ask @Bischoff for any question about it but this is already covered

@Bischoff  imho we can close this

**Comment by Bischoff** [comment]
Yes, this is already done. Just add `private_network = true` to your `main.tf` file.

Closing.

**Comment by MalloZup** [comment]
:tada: :tada: thx @Bischoff @aaannz  feel fre to use it or ask for any question :+1:
