### ISSUE TITLE
remove phantomjs from sumaform and obs repo once 3.0 testsuite gets not maintained anymore

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#296]
@mcalmer @moio @Bischoff  i decided that for the 30 testsuite we will keep phantomjs.

I just run an experimental run, and there is to much code diffrent from 31/head tests, which would need extra adaptation.

Morever the testsuite 30 is "don't touch me" mode, so i don't see any reason to add chromium as web-browser there, since would need also more effort and maintainance. ( and soon 30 will go away).

This issue is just a reminder to remove phantomjs from sumaform controller and obs repo "cucumber-testsuite" when the 30 testsuite go away

**Comment by juliogonzalez** [comment]
I seems this was fixed by this direct commit: https://github.com/moio/sumaform/commit/18007c6d294e0c567fafd1f90512d4f8cb13b243

**Comment by MalloZup** [comment]
@juliogonzalez do you still have `3.0` ? why you removed it then?

**Comment by juliogonzalez** [comment]
`3.0` goes EOL tomorrow. I did not removed it, https://github.com/moio/sumaform/commit/18007c6d294e0c567fafd1f90512d4f8cb13b243 is from @moio this morning.

**Comment by MalloZup** [comment]
@juliogonzalez @moio  ok nice :tada: 
please take care on the `gitlab` terraform files and instances that will become free !

**Comment by moio** [comment]
Sorry for not making this public yet. We need to upgrade phantomjs in the repo in order to build Grafana, so breaking the 3.0 testsuite at this time did not seem too invasive.

**Comment by juliogonzalez** [comment]
@MalloZup, @Bischoff will take care of the instances IIRC.

As for the gitlab, sumaform, IPs, hostnames, etc, we'll keep it for around 6 months more, as requested by @kkaempf
