### ISSUE TITLE
Glance upload examples point to outdated 42.1 openSUSE version

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#30]
https://github.com/moio/sumaform/tree/master/modules/openstack#upload-base-images-via-glance

We don't have the opensuse-leap42.1 there:
http://download.opensuse.org/repositories/Cloud:/OpenStack:/Master/

**Comment by moio** [comment]
This has to be updated to 42.2 and tested, agreed.

**Comment by MalloZup** [comment]
@moio, i'm closing this, since is not more relevant atm ( and the openstack modules is not there anymore)
