### ISSUE TITLE
[CLOUD] Our images need a to big flavor

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#33]
Recently i did a test with a friend from cloud, and we tried out , sumaform for openstack a cloud.

The problem was, that image want a xl.flavor in small cloud. 

Byside of this, with a small other image the test went well.

**Comment by moio** [comment]
That depends on the OpenStack Cloud installation you are working with - [flavors are not fixed, OpenStack Cloud admins can change their meaning](http://docs.openstack.org/admin-guide/compute-flavors.html).

We tested that setting and it worked on the specific Cloud that we were targeting (the HackWeek internal SUSE Cloud). In case you find any default setting in this project to be inadequate for the current internal SUSE OpenStack Cloud instance feel free to update them.

Thanks for reporting
