### ISSUE TITLE
Instances (including SUMA server) have no /etc/fstab

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#334]
The VMs created by sumaform have no /etc/fstab file.

This was not a problem until recently (apart when testing on SLE12 or SLE12 SP1).

But now even a SLE12 SP3 machine, when rebooted, has its root filesystem mounted read-only. That then makes eth0 remain down and the instance is unreacheable.

It should either be fixed while creating the images or from salt states. Currently we work around it with a hack in the test suite, but that's only a temporary measure.

**Comment by mcalmer** [comment]
@moio - I found the reason. When we build the kiwi images we set:

    <type image="vmx" filesystem="ext4" boot="vmxboot/suse-SLES12" format="qcow2"
              bootloader="grub2"
              kernelcmdline="root=/dev/vda1 disk=/dev/vda nomodeset LOCAL_BOOT=yes elevator=noop" 
              boottimeout="0">

The `LOCAL_BOOT=yes` cause the kiwi linuxrc to not generate a fstab. If we just remove this option
a fstab gets generated.

**Comment by moio** [comment]
I do not really understand what this (apparently KIWI-specific) variable does. Nor I can find any documentation about it :cry:

**Comment by mcalmer** [comment]
I read the source to find out :-)

**Comment by mcalmer** [comment]
@moio  - How to fix this? Change the images, rebuild and call everywhere `terraform destroy` or do we need to rename all the images and adapt the code in sumaform to use the new image?

**Comment by moio** [comment]
@mcalmer images have been patched and rebuilt. I recommand tainting the images on affected hosts (or running `terraform destroy` if anything else can also be discarded).

**Comment by mcalmer** [comment]
@moio Marcus told me, that we have an empty fstab in the overlay file (root.tar.bz2). We should try to remove it as well.

**Comment by moio** [comment]
I removed those and images are now rebuilding

**Comment by moio** [comment]
Images built. @Bischoff, can you please run a quick check with, say, a SLES client or minion and see if the problem is indeed solved? In that case the issue can be closed. Thanks!

**Comment by Bischoff** [comment]
It seems fixed:
```
ebi2-client:~ # cat /etc/fstab 
UUID=8ff1d7cf-e303-429b-b30f-6ed44d0571ca / ext4 defaults 1 1
ebi2-client:~ # reboot
Connection to ebi2-client.tf.local closed by remote host.
Connection to ebi2-client.tf.local closed.
ebischoff@ix64ph1078:~/test> ssh root@ebi2-client.tf.local
Password: 
Last login: Mon May 14 15:47:49 2018 from 10.162.2.78
ebi2-client:~ # cat /etc/os-release 
NAME="SLES"
VERSION="15"
```
Closing.
