### ISSUE TITLE
remove running variable or update provider

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#353]
the running variable is not anymore supported in the new terraform libvirt, it was never working.

https://github.com/dmacvicar/terraform-provider-libvirt/pull/301

**Comment by MalloZup** [comment]
i can get behaviour back with PR dmacvicar/terraform-provider-libvirt#257 i need only to rebase and change variable name

**Comment by moio** [comment]
That sounds like a better plan to me

**Comment by MalloZup** [comment]
https://github.com/dmacvicar/terraform-provider-libvirt/pull/301

**Comment by MalloZup** [comment]
fixed by last version
