### ISSUE TITLE
Package more recent terraform-libvirt-provider

### ISSUE THREAD

**Issue by Bischoff** [moio/sumaform#385]
Please update terraform-libvirt-provider version in home:SilvioMoioli:tools. Rationale:

1. Current package is 8 months old.

2. With it, I cannot define private networks handled by sumaform:
```
Cannot map '...': we are not waiting for DHCP lease and no IP has been provided
```

If I recompile and install latest terraform-libvirt-provider manually, this problem goes away.

3. I also need this fix for the non-DHCP networks:

    https://github.com/dmacvicar/terraform-provider-libvirt/pull/314

(PR submitted and not accepted yet)

**Comment by MalloZup** [comment]
@Bischoff i am closing this in favor for 
https://github.com/moio/sumaform/issues/285

which i will adreess on the issue mentioned.
