### ISSUE TITLE
[Centos7] Image, cannot access it without a Key

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#39]
All image that we have, we can access them with password ssh. 

The centos7 image, to access it through ssh, we have to first log in control-node, then goto centos7

**Comment by MalloZup** [comment]
https://github.com/moio/sumaform/pull/40

**Comment by MalloZup** [comment]
https://access.redhat.com/solutions/336773

**Comment by moio** [comment]
This is still reproducible.

All sumaform images should be accessible with password linux via ssh out of the box, so this is an issue of the centos7 image that should be fixed.

**Comment by MalloZup** [comment]
@moio , did a test with @mbologna , and we found out that my host, /etc/sshd_config was not having the ```PasswordAuthentication no .``` 

Modifying the host sshd_config file, solved the issue.  

The only strange stuff, was that i could access openSUSE/SUSE systems without no modification.

**Comment by moio** [comment]
@MalloZup what host are you talking about? A minion created by sumaform?

**Comment by MalloZup** [comment]
@moio, yes minion created with sumaform.

**Comment by moio** [comment]
@MalloZup then /etc/sshd_config has to be fixed at image creation time, so that the image ships with correct /etc/sshd_config.

**Comment by moio** [comment]
Clarified via chat: this was a client configuration issue only (ssh_config on the sumaform host contained `PasswordAuthentication no`).

Sorry for the noise, closing.
