### ISSUE TITLE
Move Devel_Galaxy_cucumber_testsuite_repo to an external repo

### ISSUE THREAD

**Issue by juliogonzalez** [moio/sumaform#403]
Current repository Devel_Galaxy_cucumber_testsuite_repo at https://github.com/moio/sumaform/blob/master/salt/repos/controller.sls will not work as soon as we have a public CI.

I can only see two dependencies there: phantomjs (AFAIK we don't use it anymore) and twopence (I guess we took it from https://build.opensuse.org/package/show/devel:tools/twopence so our stuff doesn't break if there are updates there).

It seems we have two alternatives:

1. Move it to a new subproject at https://build.opensuse.org/project/show/systemsmanagement:Uyuni
2. Move it to https://build.opensuse.org/project/show/systemsmanagement:sumaform

Both options are valid for me. We just need to pick one, copy the package there, and as soon as we have the build, update sumaform.

Ping @moio @MalloZup, I can help, but we need to decide where the twopence should live.

**Comment by moio** [comment]
Analysis is correct, we should just copypac twopence to https://build.opensuse.org/project/show/systemsmanagement:sumaform:tools ("Software for sumaformed Virtual Machines") and update repo URLs.

Thanks

**Comment by juliogonzalez** [comment]
@moio can you give me rights to copy the package to https://build.opensuse.org/project/show/systemsmanagement:sumaform:tools or do it yourself?

**Comment by juliogonzalez** [comment]
@MalloZup, at `salt/controller/init.sls`we have:
```
# HACK: currently we need this exact version
phantomjs_2.0_cucumber_repo:
  pkg.installed:
  - name: phantomjs
  - version: 2.0.0
```

Do we still need it?

**Comment by MalloZup** [comment]
until 3.0 is supported run on ci

**Comment by moio** [comment]
@juliogonzalez permissions added. 3.0 can be phased out early next year I would say.
