### ISSUE TITLE
Possible bug at branch selection for openstack controller

### ISSUE THREAD

**Issue by juliogonzalez** [moio/sumaform#427]
https://github.com/moio/sumaform/blob/master/modules/openstack/controller/main.tf#L7 has:
```
    "3.2-released" = "Manager"
```
While https://github.com/moio/sumaform/blob/master/modules/libvirt/controller/main.tf#L7 has:
```
    "3.2-released" = "Manager-3.2"
```
I think the branch for openstack should be "Manager-3.2" as well, when version is "3.2-released".

**Comment by juliogonzalez** [comment]
After checking with @Bischoff seems to be a bug. @moio can you confirm?

**Comment by moio** [comment]
Yes
