### ISSUE TITLE
Avahi hosts through bridged network

### ISSUE THREAD

**Issue by cbbayburt** [moio/sumaform#44]
I just found out that I can reach the machines through the bridged network (from `suse.de` network) using the `tf.local` domains.
But what I had to do is make sure that the `UDP` port `5353` is open in the firewall on the calling machine.

Maybe this is a good point to mention in the readme.

https://wiki.archlinux.org/index.php/avahi#Firewall

**Comment by moio** [comment]
@cbbayburt thanks for reminding me, this is something I had in the back of my mind for a while!

https://github.com/moio/sumaform/blob/master/TROUBLESHOOTING.md#q-how-can-i-work-around-name-resolution-problems-with-tflocal-mdnszeroconfbonjouravahi-names
