### ISSUE TITLE
Devel:Galaxy:Manager:Head repo expects to be layered on SLES 12 SP1, should be SP2

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#50]
On this repo-file, we have " sles-12sp1", but the head repo, can be also for sp2.

https://github.com/moio/sumaform/blob/master/salt/suse-manager/repos.d/Devel_Galaxy_Manager_Head.repo

We should add sle-12sp2 in name conventions

- [ ]  [Devel_Galaxy_Manager_Head_12sp1] 
- [ ] [..] 

I discovered it by searching where the tools are builded

**Comment by moio** [comment]
Actually as the next HEAD is now decided to be on SP2, it would make more sense to hardcode it for SP2 only. It does not make sense any more to try to build (or test!) HEAD on SP1.

**Comment by MalloZup** [comment]
yes, true, i figure it out later.  :v:

**Comment by moio** [comment]
Fixed.
