### ISSUE TITLE
Ubuntu desktop is used instead of server

### ISSUE THREAD

**Issue by ktsamis** [moio/sumaform#508]
From the size of the images:

http://ftp.fau.de/ubuntu-releases/bionic/

ubuntu-18.04.2-live-server-amd64.iso           834M 
ubuntu-18.04.2-desktop-amd64.iso               1.9G  

and the size of our image is ~1.9G. It takes way too long to download and I don't think the desktop is needed. We really should move it away from github as well (it times out way too often) but that's another issue.

**Comment by moio** [comment]
We use Ubuntu Server as the base image:

https://github.com/moio/sumaform-images/blob/master/ubuntu1804.json#L19

Live Server is different and does not contain many packages. IIRC that one was tested too but did not result in a smaller image - missing packages were just downloaded at build time.

Moreover this is a bug for sumaform-images, not sumaform.

I would close this issue.

**Comment by ktsamis** [comment]
You are right, I didn't see the source, just saw the sizes and misunderstood, closing this.
