### ISSUE TITLE
Sumaform fails,  by refreshing repos

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#55]
### How to Reproduce:

1)Take the testsuite.main.tf as an example.
2) In the client module we add a build repo.

3) Take the ```refresh-client-repo``` state 
https://github.com/moio/sumaform/blob/master/salt/client/repos.sls#L20.

This state, require the recently added ```default``` state. In this default, we have pkg.uptodate cmd.

The issue is following: 
In the state we add a new repos, and we have first to accept the gpg-keys and metadata of repos, before trying to update the repo, otherwise we have  a zypper failure, that break the wholes states.

#### Remarks:
I cited the client module, but this issue concern all repos.sls state for each module, where we add repos.

##### HOW i Fixed it:

```console
refresh-accept-client-repos:
  cmd.run:
    - name: zypper --non-interactive --gpg-auto-import-keys refresh
    - require:
      - file: testsuite-build-repo
      - file: testsuite-suse-manager-repo

update-client-pkgs:
  cmd.run:
    - name: zypper --non-interactive --gpg-auto-import-keys refresh
    - require:
      - sls: default
```
@moio , i didn't look to much in the detail of your new machinery of adding/refreshing repos.

This is how i fixed it, and works stable for each module. So we need to separe the update pkgs from the new-repos installation, and we need to add this 2 state-cmd for each repo.sls (minion, server, client)
If you have a more elegant way, but imho is quite elegant.

If you like the approach i will do a pr next week

**Comment by moio** [comment]
Fixed, thanks for reporting.
