### ISSUE TITLE
Timezone settings

### ISSUE THREAD

**Issue by hustodemon** [moio/sumaform#59]
My machines and also the testing ones have the timezone set up to UTC.
Customers OTOH have correctly set up timezones (not only in the bare system, other TZ-related settings (like postgres) are also different against sumaform machines). These differences should be examined, corresponding settings should be made configurable in sumaform and our test infra should be adjusted accordingly.

# Deviations
(There might be more of them.)
## `timedatectl`
- sumaform:
```
      Local time: Do 2017-01-19 10:07:37 UTC
  Universal time: Do 2017-01-19 10:07:37 UTC
        RTC time: Do 2017-01-19 10:07:44
        Timezone: Etc/UTC (UTC, +0000)
     NTP enabled: n/a
NTP synchronized: no
 RTC in local TZ: no
```
- manager.suse.de
```
      Local time: Do 2017-01-19 11:08:21 CET
  Universal time: Do 2017-01-19 10:08:21 UTC
        RTC time: Do 2017-01-19 10:08:21
        Timezone: Europe/Berlin (CET, +0100)
     NTP enabled: n/a
NTP synchronized: no
 RTC in local TZ: no
```
## `postgresql.conf`
- sumaform machine: `timezone = 'UTC`
- manager.suse.de:  `timezone = 'posixrules`

**Comment by moio** [comment]
As far as I can see this is fixed now in sumaform. Test infrastructure is up to @MalloZup as usual.
