### ISSUE TITLE
Accessing someone else VM with sumaform

### ISSUE THREAD

**Issue by MalloZup** [moio/sumaform#6]
## Description:

Usually i put in the browser suma3pg.tf.local to access my server.
I noticed that i was accessing someone other else server, with 5 clients. 

This happened also with ssh root@suma3pg.tf.local

Discussing with @mbologna , he sayed  ", you can access it because of avahi published to the internal network"

**Comment by moio** [comment]
In the branch I am working on I added the ability to set a global prefix, like your username, to all the machines. That way people will not get confused.

**Comment by MalloZup** [comment]
@moio, ok  seems a good solution. :)

**Comment by moio** [comment]
Fixed in master now. Thanks for reporting
