### ISSUE TITLE
Prevent "resource already exists" or "resource not found" errors in libvirt

### ISSUE THREAD

**Issue by moio** [moio/sumaform#74]
It is not clear whether those errors from terraform-provider-libvirt are always actually correctly reported.

It boils down to the following question: if a resource had to be created but was found already, should the provider simply proceed doing nothing and reporting no error? Conversely: if a resource had to be destroyed but was found not to be there in the first place, is an error appropriate?

I have the impression the AWS provider does not report errors in those cases - but that has to be double checked.

The result of this investigation could be a PR to terraform-provider-libvirt.

**Comment by MalloZup** [comment]
After some investigation, this issue is due only on sumaform design.
We should use var rvolume volume.id to avoid race condition when we create a volume in base, and the use this in host. After my research, in order to do so, we need a big design change.
@moio maybe i am  wrong, but i don t see otherwise how to pass the volume.id

**Comment by moio** [comment]
@MalloZup can you try adding a [depends_on](https://www.terraform.io/docs/configuration/outputs.html#depends_on) clause to the `base` module `configuration` output and report back if that helps?

Eg. `modules/libvirt/base/main.tf`:

```hcl
...
output "configuration" {
  depends_on = ["libvirt_volume.volumes"]
  value = {
    network_name = "${var.network_name}"
```

**Comment by MalloZup** [comment]
@moio  ok,  good hint, this i didnt try out.

**Comment by moio** [comment]
Should be fixed by the referenced PR!

**Comment by MalloZup** [comment]
Ok cool  i will test this soon, tbis is a great fix tbat can open new worlds!
